# Generated by Django 5.1.3 on 2024-12-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threemoduleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Phone_number',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Phone_number',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Image',
        ),
        migrations.AlterField(
            model_name='student',
            name='Age',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Age',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
